#!/bin/bash

TITLE="$*"
SLUG=$(echo "$TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/ /-/g')
DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
FILE="_posts/$DATE-$SLUG.md"

cp ./_templates/new_post.md "$FILE"
sed -i '' "s/title: \"\"/title: \"$TITLE\"/" "$FILE"
sed -i '' "s/date:/date: $DATE $TIME/" "$FILE"

echo "Created $FILE"